### PR TITLE
Add datetime tests

### PR DESCRIPTION
**Pull request by judofyr**

### CODE REVIEW

**Review by atombender — APPROVED** [review]

**Comment by j33ty** [comment]
GROQ spec doesn't say anything about the timestamp precision in `dateTime()`. Is that intentionally omitted?

**Comment by atombender** [comment]
Since the string format only has second precision, that might be enough.

**Comment by j33ty** [comment]
[This test](https://github.com/sanity-io/groq-test-suite/pull/8/files#diff-cad4ffc99519cd115f752fce0dc0fa28938458de6844faa95813cb122a1c15feR11) says sub-second precision is valid though.

**Comment by atombender** [comment]
Looks like RFC 3339 has sub-second precision — I didn't think that was standard:

```
time-secfrac    = "." 1*DIGIT
```

**Comment by judofyr** [comment]
RFC3339 supports fractional seconds, and I don't see any reason to _reject_ fractional seconds. We've also talked about increasing the fidelity of `createdAt` and `updatedAt` so having proper support for fractional seconds make sense. This will probably require some updates in the spec as well.

One complication is that JavaScript only deals with milliseconds. You can't have a `Date` that represent fractional milliseconds.

I propose that the spec will require that `dateTime` *must* be capable of storing milliseconds, and *may* have finer granularity. For `string(…)` and JSON representation the rules are as follows:

1. If there are no millisecond stored in the `dateTime`, return a RFC3339 without any fractional seconds.
2. If there are milliseconds (and nothing finer) stored in the `dateTime`, return a RFC3339 with 3 digits of fractional seconds.
3. If there are even finer granularity, then it's implementation specific how many digits are returned.

Thoughts?

**Comment by atombender** [comment]
Sounds good to me.

**Comment by j33ty** [comment]
Yeah, sounds good.

**Review by j33ty — APPROVED** [review]

**Pull request merged**
