### PR TITLE
Add more performance tests against movie dataset

### PR DESCRIPTION
**Pull request by atombender**
Some suggestions for performance tests that exercise more scenarios.

### CODE REVIEW

**Review by judofyr — APPROVED** [review]
I see the point that the results here become very noisy. I still think it's valuable to have them here, but maybe we need functionality for storing them alongside. (`resultFromFile: foo.json`).

**Comment by atombender** [comment]
Or maybe one test file per test?

**Comment by judofyr** [comment]
Good idea. That works today without any changes to the build script.

**Comment by atombender** [comment]
Split tests and also added a handful more.

**Comment by atombender** [comment]
I put this in each file:

> name: "perf / movies"

Does the test suite require unique names for each file, @judofyr?

**Comment by judofyr** [comment]
> Does the test suite require unique names for each file, @judofyr?

Nope. It guarantees that the generated `_id`s are unique so everything should work fine.

**Pull request merged**
